name: 05 -1 - Event filter and activities

on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: echo "Running whenever a PR is openedor synchronized ANS base branch is main"